name: Anass El Houd
title: Anass El Houd | AI Engineer & Data Scientist
description: Artificial Intelligencce (ML/DL) Enginner and Data Scientist
url: https://aelhoud.me
baseurl: https://aelhoud.me
email: anass.elhoud@gmail.com
cover: https://aelhoud.me/img/og.png
logo: https://aelhoud.me/img/emojis/technologist.png
resume: https://aelhoud.me/img/Anass_ELHOUD_CV_Updated_compressed.pdf
social:
   - title: email
    url: mailto:anass.elhoud@gmail.com
  - title: instagram
    url: https://instagram.com/anasselhoud
  - title: github
    url: https://github.com/anasselhoud
  - title: linkedin
    url: https://www.linkedin.com/in/anass-elhoud
    
# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
